version: '3'
services:
  mongo:
    image: mongo:3.2-jessie
    ports: 
      - "27017:27017"
    container_name:  mongo-docker
    network_mode:  host
    volumes:
      - '/Desktop/data/mysql:/data/db'

  spring:
    image:  movie-app_server:v02
    build:  movie-service/
    restart:  always
    network_mode:  host
    container_name:  spring-docker
    depends_on:
      -  mongo
    ports:
      -  8080:8080
    expose:
      -  8080

  config:
    image: config-server:v01
    restart: always
    ports:
      - 8891:8891
    
  registry:
    image: eureka-server:v01
    restart: always
    depends_on:
      - config
    ports:
      - 8888:8888

  gateway:
    image: apigateway:v01
    restart: always
    depends_on:
      - config
    ports:
      - 8092:8092
