version: '3'
services:
  mongo:
    image: mongo:3.2-jessie
    ports: 
      - "27017:27017"
    container_name:  mongo-docker
    network_mode:  host
    volumes:
      - '/Desktop/data/mysql:/data/db'

  spring:
    image:  movie-app_service:v01
    build:  movie-service/
    restart:  always
    network_mode:  host
    container_name:  spring-docker
    depends_on:
      -  mongo
    ports:
      -  8080:8080
    expose:
      -  8080

  config:
    image: config-server:v03
    restart: always
    
  registry:
    image: eureka-server:v03
    restart: always
    depends_on:
      - config
    ports:
      - 9090:9090

  gateway:
    image: apigateway-server:v03
    restart: always
    depends_on:
      - config
    ports:
      - 8092:8092
